version: '3.8'

services:
  mariadb:
    image: mariadb:latest
    container_name: chargeCode-mariadb
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: userManager  # Change this to your desired database name
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: chargeCode-phpmyadmin
    environment:
      PMA_HOST: mariadb  # Change this to match the MariaDB service name
      PMA_USER: root
      PMA_PASSWORD: root
    ports:
      - "8080:80"
    depends_on:
      - mariadb  # Change this to match the MariaDB service name

  myapp:
    build:
      dockerfile: Dockerfile
    container_name: usermanager-golang
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_HOST: mariadb  # Change this to match the MariaDB service name
      MYSQL_PORT: "3306"
      MYSQL_DB: userManager  # Change this to your desired database name
      MAX_CHARGE_CODE_AMOUNT: 1000000
      MIN_CHARGE_CODE_AMOUNT: 1000000
      MAX_TRANSACTION_AMOUNT: 2000000
      MIN_TRANSACTION_AMOUNT: -200000
      MAX_PAGE: 100
      MAX_PAGE_SIZE: 30
      APPLICATION_PORT: 4238
      MYSQL_URL: root:root@tcp(mariadb)/
#      DATABASE_URL: "root:root@tcp(mariadb:3306)/"  # Change this to match the MariaDB service name
    ports:
      - "4238:4238"
    depends_on:
      - mariadb  # Change this to match the MariaDB service name
    links:
      - mariadb  

volumes:
  mariadb_data:
