// Code generated by swaggo/swag. DO NOT EDIT.

package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1/chargeCode": {
            "get": {
                "description": "Get all chargeCode.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "ChargeCode"
                ],
                "summary": "Get chargeCodes",
                "operationId": "get-all-chargeCode",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/delivery.ChargeCode"
                            }
                        }
                    }
                }
            },
            "put": {
                "description": "Update a chargeCode using the provided data.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "ChargeCode"
                ],
                "summary": "Update a chargeCode",
                "parameters": [
                    {
                        "description": "ChargeCode object to update",
                        "name": "chargeCode",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/delivery.ChargeCode"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/delivery.ChargeCode"
                        }
                    }
                }
            },
            "post": {
                "description": "Create a new chargeCode using the provided data.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "ChargeCode"
                ],
                "summary": "Create a new chargeCode",
                "parameters": [
                    {
                        "description": "ChargeCode object to create",
                        "name": "CreateChargeCodeMode",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/delivery.CreateChargeCodeMode"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/delivery.ChargeCode"
                        }
                    }
                }
            }
        },
        "/api/v1/chargeCode/code/{code}": {
            "get": {
                "description": "Get a chargeCode by their unique Code.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "ChargeCode"
                ],
                "summary": "Get chargeCode by Code",
                "operationId": "get-chargeCode-by-code",
                "parameters": [
                    {
                        "type": "string",
                        "description": "chargeCode Code",
                        "name": "code",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/delivery.ChargeCode"
                        }
                    }
                }
            }
        },
        "/api/v1/chargeCode/user/{userId}": {
            "get": {
                "description": "Get a user chargeCode by their unique userId.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "ChargeCode"
                ],
                "summary": "Get user chargeCodes",
                "operationId": "get-chargeCode-by-userId",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "user id",
                        "name": "userId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/delivery.ChargeCode"
                        }
                    }
                }
            }
        },
        "/api/v1/chargeCode/{id}": {
            "get": {
                "description": "Get a chargeCode by their unique ID.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "ChargeCode"
                ],
                "summary": "Get chargeCode by ID",
                "operationId": "get-chargeCode-by-id",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "chargeCode ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/delivery.ChargeCode"
                        }
                    }
                }
            },
            "delete": {
                "description": "Delete a chargeCode by their unique ID.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "ChargeCode"
                ],
                "summary": "Delete chargeCode by ID",
                "operationId": "delete-chargeCode-by-id",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "chargeCode ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/v1/transaction": {
            "get": {
                "description": "Get all transactions.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Transaction"
                ],
                "summary": "Get transactions",
                "operationId": "get-all-transactions",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/delivery.Transaction"
                            }
                        }
                    }
                }
            },
            "post": {
                "description": "Create a new Transaction using the provided data.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Transaction"
                ],
                "summary": "Create a new Transaction",
                "parameters": [
                    {
                        "description": "Transaction object to create",
                        "name": "Transaction",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/delivery.Transaction"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/delivery.Transaction"
                        }
                    }
                }
            }
        },
        "/api/v1/transaction/charge": {
            "post": {
                "description": "Create a new ChargeCodeTransaction using the provided data.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Transaction"
                ],
                "summary": "Create a new ChargeCodeTransaction",
                "parameters": [
                    {
                        "description": "ChargeCodeTransaction object to create",
                        "name": "ChargeCodeTransaction",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/delivery.ChargeCodeTransaction"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/delivery.ChargeCodeTransaction"
                        }
                    }
                }
            }
        },
        "/api/v1/transaction/user/totalNumber/{userId}": {
            "get": {
                "description": "Get Total a Transaction by their unique user ID.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Transaction"
                ],
                "summary": "Get Total Transaction by user ID",
                "operationId": "get-total-transaction-by-user-id",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "user ID",
                        "name": "userId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/delivery.Transaction"
                        }
                    }
                }
            }
        },
        "/api/v1/transaction/user/{userId}": {
            "get": {
                "description": "Get a Transactions by their unique user ID.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Transaction"
                ],
                "summary": "Get Transactions by user ID",
                "operationId": "get-transactions-by-user-id",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "user ID",
                        "name": "userId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/delivery.Transaction"
                        }
                    }
                }
            }
        },
        "/api/v1/transaction/{id}": {
            "get": {
                "description": "Get a Transaction by their unique ID.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Transaction"
                ],
                "summary": "Get Transaction by ID",
                "operationId": "get-transaction-by-id",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "transaction ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/delivery.Transaction"
                        }
                    }
                }
            }
        },
        "/api/v1/user": {
            "put": {
                "description": "Update a User using the provided data.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Users"
                ],
                "summary": "Update a User",
                "parameters": [
                    {
                        "description": "User object to update",
                        "name": "User",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/delivery.User"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/delivery.User"
                        }
                    }
                }
            }
        },
        "/api/v1/user/balance/{userId}": {
            "get": {
                "description": "Get a user balance by their unique id.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Users"
                ],
                "summary": "Get user balance by id",
                "operationId": "get-user-balance-by-id",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "User id",
                        "name": "userId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "number"
                        }
                    }
                }
            }
        },
        "/api/v1/user/chargeCode/{chargeCodeId}": {
            "get": {
                "description": "Get all List Of Users Use CargeCode.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Users"
                ],
                "summary": "Get List Of Users Use CargeCode",
                "operationId": "get-all-Users",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User chargeCode id",
                        "name": "chargeCodeId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/delivery.ChargeCode"
                            }
                        }
                    }
                }
            }
        },
        "/api/v1/user/{phoneNumber}": {
            "get": {
                "description": "Get a user by their unique phoneNumber.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Users"
                ],
                "summary": "Get user by phoneNumber",
                "operationId": "get-user-by-phoneNumber",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User phoneNumber",
                        "name": "phoneNumber",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/delivery.User"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "delivery.ChargeCode": {
            "type": "object",
            "required": [
                "amount",
                "code",
                "current_uses",
                "max_uses"
            ],
            "properties": {
                "amount": {
                    "type": "number"
                },
                "charge_code_id": {
                    "type": "integer"
                },
                "code": {
                    "type": "string"
                },
                "current_uses": {
                    "type": "integer"
                },
                "max_uses": {
                    "type": "integer"
                }
            }
        },
        "delivery.ChargeCodeTransaction": {
            "type": "object",
            "required": [
                "ChargeCodeID",
                "phoneNumber"
            ],
            "properties": {
                "ChargeCodeID": {
                    "type": "integer"
                },
                "phoneNumber": {
                    "description": "TransactionID int ` + "`" + `json:\"transaction_id\"` + "`" + `",
                    "type": "string"
                }
            }
        },
        "delivery.CreateChargeCodeMode": {
            "type": "object",
            "required": [
                "amount",
                "code",
                "current_uses",
                "max_uses"
            ],
            "properties": {
                "amount": {
                    "type": "number"
                },
                "code": {
                    "type": "string"
                },
                "current_uses": {
                    "type": "integer"
                },
                "max_uses": {
                    "type": "integer"
                }
            }
        },
        "delivery.Transaction": {
            "type": "object",
            "required": [
                "phoneNumber"
            ],
            "properties": {
                "amount": {
                    "type": "number"
                },
                "phoneNumber": {
                    "description": "TransactionID int     ` + "`" + `json:\"transaction_id\"` + "`" + `",
                    "type": "string"
                }
            }
        },
        "delivery.User": {
            "type": "object",
            "required": [
                "PhoneNumber"
            ],
            "properties": {
                "Balance": {
                    "type": "number"
                },
                "PhoneNumber": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
